# Generated by Django 5.1.7 on 2025-03-23 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('curp', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_social.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Carta de asignación', 'Carta de asignación'), ('Reporte parcial', 'Reporte parcial'), ('Evaluación de desempeño', 'Evaluación de desempeño'), ('Carta de término', 'Carta de término')], max_length=50)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('subido', models.BooleanField(default=False)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_social.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas_requeridas', models.IntegerField(default=480)),
                ('horas_realizadas', models.IntegerField(default=0)),
                ('actividades', models.TextField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_social.institucion')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_social.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reporte', models.IntegerField()),
                ('archivo', models.FileField(upload_to='reportes/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_social.serviciosocial')),
            ],
        ),
    ]
