# Generated by Django 5.1.7 on 2025-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
