# Generated by Django 5.1.7 on 2025-04-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_social', '0004_alter_carrera_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendocumentos',
            name='servicio_social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicio_social.serviciosocial'),
        ),
    ]
