# Generated by Django 5.1.7 on 2025-04-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_social', '0005_resumendocumentos_servicio_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumendocumentos',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='resumendocumentos',
            name='prestador',
        ),
    ]
